[package]
name = "s2c10"
version = "0.1.0"
authors = ["pink"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
base64 = "0.11.0"