[package]
name = "s2c9"
version = "0.1.0"
authors = ["PinkP4nther <0x0090@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
