[package]
name = "s1c1"
version = "0.1.0"
authors = ["pinky <0x0090@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.0"
base64 = "0.11.0"